controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: status_homepage
        permanent: true # Redirection 301